/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rsolci.kafkaops

import com.rsolci.kafkaops.commands.MainCommand

fun main(args: Array<String>) = MainCommand().main(args)
