/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.rsolci.kafkaops

import io.github.rsolci.kafkaops.commands.MainCommand

fun main(args: Array<String>) = MainCommand().main(args)
