name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and store artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@fec4a42eb0c83154e5c9590748ba8337949c5701
        with:
          arguments: build --info

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: kafka-ops
          path: ./build/libs/kafka-ops.jar

  relase:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: kafka-ops

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kafka-ops.jar

  docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: kafka-ops
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rsolci/kafka-ops:latest
