name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and store artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build --info

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: kafka-ops
          path: ./build/libs/kafka-ops.jar

  relase:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: kafka-ops

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kafka-ops.jar

  docker:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: kafka-ops
          path: build/libs

      - name: Build image
        env:
          IMAGE_TAG: latest
        run:
          docker build -t rsolci/kafka-ops:$IMAGE_TAG .

      - name: Push image
        env:
          IMAGE_TAG: latest
        run:
          docker push rsolci/kafka-ops:$IMAGE_TAG

#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: rsolci/kafka-ops:latest
